bin/open: improve script to be more reliable

diff --git a/bin/open b/bin/open
--- a/bin/open
+++ b/bin/open
@@ -1,3 +1,20 @@
 #!/bin/sh
-# This is for having similar behaviour for open on Linux like on MacOS
-[ -x /usr/bin/open ] && exec /usr/bin/open "$@" || exec xdg-open "$@"
+# This is for having an simple drop-in replacement on linux for 
+# the MacOS open command
+
+if [ "x$(uname)" = "xDarwin" ]; then
+    # On MacOS just use the open command provided, if available
+    if [ -x /usr/bin/open ]; then
+        exec /usr/bin/open "$@"
+    else
+        echo "Error: No /usr/bin/open does not seem to work, aborting... "
+        exit 2
+    fi
+elif command -v xdg-open > /dev/null; then
+    # Else we assume it's some kind of FreeDesktop based linux where xdg-open is available.
+    exec xdg-open "$@"
+else
+    # TODO: maybe expand this in the future for other file opening applications like maybe rifle?
+    echo "Error: no suitable program launcher like xdg-open found."
+    exit 1
+fi
