4git: rebase: add more tests and fixes

diff --git a/4git/bin/4git-rebase b/4git/bin/4git-rebase
--- a/4git/bin/4git-rebase
+++ b/4git/bin/4git-rebase
@@ -5,7 +5,6 @@ set -u
 d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source "$d/4gitinit.sh"
 
-workspace_branch="$("$d"/4git-branch --base)"
 
 usage() {
     echo "Usage: 4git-rebase  [ --current | --select | --select-all | --to-leaf | --from-leaf ]"
@@ -17,29 +16,31 @@ git_rebase_cmd() {
 }
 
 get_upstream_branch() {
-    branch="$("$d"/4git-branch-select || true)"
+    branch="$(4git-branch-select || true)"
     if [ -z "$branch" ]; then
-        echo "ERROR: no intermediary branch to rebase from out has been picked"
+        echo "ERROR: no intermediary branch to rebase from"
         exit 1
     fi
 }
 
 get_leaf_branch() {
-    leaf_branch="$("$d"/4git-branch-select --subbranch || true)"
+    leaf_branch="$(4git-branch-select --subbranch || true)"
     if [ -z "$leaf_branch" ]; then
-        echo "ERROR: no leaf branch to rebase to has been picked"
+        echo "ERROR: no leaf branch to rebase to"
         exit 1
     fi
 }
 
-case "$1" in
+workspace_branch="$(4git-branch --base)"
+
+case "${1:---help}" in
     --help) usage ;;
     --current)
-        git_rebase_cmd "$workspace_branch" $(current_branch)
+        git_rebase_cmd "$workspace_branch" "$(current_branch)"
         ;;
     --select)
         leaf_branch=$(get_leaf_branch)
-        git_rebase_cmd "$workspace_branch" $(branch)
+        git_rebase_cmd "$workspace_branch" "$leaf_branch"
         ;;
     --select-all)
         # this is first the cut off point, so the base branch
